export const FETCH_BIKES_REQUEST = 'FETCH_BIKES_REQUEST';
export const FETCH_BIKES_FAILURE = 'FETCH_BIKES_FAILURE';
export const FETCH_BIKES_SUCCESS = 'FETCH_BIKES_SUCCESS';
// export const SET_BIKES = 'SET_BIKES';
export const SET_BIKES_FILTER = 'SET_BIKES_FILTER';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CHECKOUT_CART = 'CHECKOUT_CART';
